"""Initial migration

Revision ID: 49ebb3edbbe1
Revises: 
Create Date: 2025-12-14 23:53:16.725215

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '49ebb3edbbe1'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('daily',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('aplicacion', sa.String(length=64), nullable=False),
    sa.Column('repo', sa.Integer(), nullable=False),
    sa.Column('proveedor', sa.Text(), nullable=True),
    sa.Column('created_on', sa.DateTime(), nullable=True),
    sa.Column('num_bugs', sa.Integer(), nullable=False),
    sa.Column('num_vulnerabilities', sa.Integer(), nullable=False),
    sa.Column('num_code_smells', sa.Integer(), nullable=False),
    sa.Column('num_quality', sa.Integer(), nullable=False),
    sa.Column('num_analisis', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('aplicacion')
    )
    with op.batch_alter_table('daily', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_daily_repo'), ['repo'], unique=True)

    op.create_table('historico',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('repo', sa.String(length=64), nullable=False),
    sa.Column('aplicacion', sa.String(length=64), nullable=True),
    sa.Column('fecha', sa.String(length=64), nullable=True),
    sa.Column('bugs', sa.Integer(), nullable=False),
    sa.Column('reliability_rating', sa.Integer(), nullable=False),
    sa.Column('reliability_label', sa.String(length=64), nullable=True),
    sa.Column('vulnerabilities', sa.Integer(), nullable=False),
    sa.Column('security_rating', sa.Integer(), nullable=False),
    sa.Column('security_label', sa.String(length=64), nullable=True),
    sa.Column('code_smells', sa.Integer(), nullable=False),
    sa.Column('sqale_rating', sa.Integer(), nullable=False),
    sa.Column('sqale_label', sa.String(length=64), nullable=True),
    sa.Column('alert_status', sa.String(length=64), nullable=True),
    sa.Column('project', sa.String(length=64), nullable=True),
    sa.Column('complexity', sa.Integer(), nullable=False),
    sa.Column('coverage', sa.Integer(), nullable=False),
    sa.Column('unit_tests', sa.String(length=64), nullable=True),
    sa.Column('ncloc', sa.Integer(), nullable=False),
    sa.Column('duplicated_line_density', sa.Integer(), nullable=False),
    sa.Column('sqale_index', sa.Integer(), nullable=False),
    sa.Column('sqale_debt_ratio', sa.Integer(), nullable=False),
    sa.Column('size', sa.String(length=64), nullable=True),
    sa.Column('dloc_label', sa.String(length=64), nullable=True),
    sa.Column('coverage_label', sa.String(length=64), nullable=True),
    sa.Column('quality_gate', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('repo')
    )
    with op.batch_alter_table('historico', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_historico_bugs'), ['bugs'], unique=True)
        batch_op.create_index(batch_op.f('ix_historico_code_smells'), ['code_smells'], unique=True)
        batch_op.create_index(batch_op.f('ix_historico_complexity'), ['complexity'], unique=True)
        batch_op.create_index(batch_op.f('ix_historico_coverage'), ['coverage'], unique=True)
        batch_op.create_index(batch_op.f('ix_historico_duplicated_line_density'), ['duplicated_line_density'], unique=True)
        batch_op.create_index(batch_op.f('ix_historico_ncloc'), ['ncloc'], unique=True)
        batch_op.create_index(batch_op.f('ix_historico_reliability_rating'), ['reliability_rating'], unique=True)
        batch_op.create_index(batch_op.f('ix_historico_security_rating'), ['security_rating'], unique=True)
        batch_op.create_index(batch_op.f('ix_historico_sqale_debt_ratio'), ['sqale_debt_ratio'], unique=True)
        batch_op.create_index(batch_op.f('ix_historico_sqale_index'), ['sqale_index'], unique=True)
        batch_op.create_index(batch_op.f('ix_historico_sqale_rating'), ['sqale_rating'], unique=True)
        batch_op.create_index(batch_op.f('ix_historico_vulnerabilities'), ['vulnerabilities'], unique=True)

    op.create_table('metricas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('repo', sa.String(length=64), nullable=False),
    sa.Column('aplicacion', sa.String(length=64), nullable=True),
    sa.Column('fecha', sa.String(length=64), nullable=True),
    sa.Column('bugs', sa.Integer(), nullable=False),
    sa.Column('reliability_rating', sa.Integer(), nullable=False),
    sa.Column('reliability_label', sa.String(length=64), nullable=True),
    sa.Column('vulnerabilities', sa.Integer(), nullable=False),
    sa.Column('security_rating', sa.Integer(), nullable=False),
    sa.Column('security_label', sa.String(length=64), nullable=True),
    sa.Column('code_smells', sa.Integer(), nullable=False),
    sa.Column('sqale_rating', sa.Integer(), nullable=False),
    sa.Column('sqale_label', sa.String(length=64), nullable=True),
    sa.Column('alert_status', sa.String(length=64), nullable=True),
    sa.Column('project', sa.String(length=64), nullable=True),
    sa.Column('complexity', sa.Integer(), nullable=False),
    sa.Column('coverage', sa.Integer(), nullable=False),
    sa.Column('unit_tests', sa.String(length=64), nullable=True),
    sa.Column('ncloc', sa.Integer(), nullable=False),
    sa.Column('duplicated_line_density', sa.Integer(), nullable=False),
    sa.Column('sqale_index', sa.Integer(), nullable=False),
    sa.Column('sqale_debt_ratio', sa.Integer(), nullable=False),
    sa.Column('size', sa.String(length=64), nullable=True),
    sa.Column('dloc_label', sa.String(length=64), nullable=True),
    sa.Column('coverage_label', sa.String(length=64), nullable=True),
    sa.Column('quality_gate', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('repo')
    )
    with op.batch_alter_table('metricas', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_metricas_bugs'), ['bugs'], unique=True)
        batch_op.create_index(batch_op.f('ix_metricas_code_smells'), ['code_smells'], unique=True)
        batch_op.create_index(batch_op.f('ix_metricas_complexity'), ['complexity'], unique=True)
        batch_op.create_index(batch_op.f('ix_metricas_coverage'), ['coverage'], unique=True)
        batch_op.create_index(batch_op.f('ix_metricas_duplicated_line_density'), ['duplicated_line_density'], unique=True)
        batch_op.create_index(batch_op.f('ix_metricas_ncloc'), ['ncloc'], unique=True)
        batch_op.create_index(batch_op.f('ix_metricas_reliability_rating'), ['reliability_rating'], unique=True)
        batch_op.create_index(batch_op.f('ix_metricas_security_rating'), ['security_rating'], unique=True)
        batch_op.create_index(batch_op.f('ix_metricas_sqale_debt_ratio'), ['sqale_debt_ratio'], unique=True)
        batch_op.create_index(batch_op.f('ix_metricas_sqale_index'), ['sqale_index'], unique=True)
        batch_op.create_index(batch_op.f('ix_metricas_sqale_rating'), ['sqale_rating'], unique=True)
        batch_op.create_index(batch_op.f('ix_metricas_vulnerabilities'), ['vulnerabilities'], unique=True)

    op.create_table('proveedor',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('aplicacion', sa.String(length=64), nullable=False),
    sa.Column('proveedor', sa.Text(), nullable=True),
    sa.Column('tipo', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('aplicacion')
    )
    op.create_table('registro',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('proceso', sa.String(length=64), nullable=False),
    sa.Column('created_on', sa.DateTime(), nullable=True),
    sa.Column('num_app', sa.Integer(), nullable=False),
    sa.Column('num_repo', sa.Integer(), nullable=False),
    sa.Column('num_bugs', sa.Integer(), nullable=False),
    sa.Column('num_quality', sa.Integer(), nullable=False),
    sa.Column('num_analisis', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('proceso')
    )
    with op.batch_alter_table('registro', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_registro_num_analisis'), ['num_analisis'], unique=True)
        batch_op.create_index(batch_op.f('ix_registro_num_app'), ['num_app'], unique=True)
        batch_op.create_index(batch_op.f('ix_registro_num_bugs'), ['num_bugs'], unique=True)
        batch_op.create_index(batch_op.f('ix_registro_num_quality'), ['num_quality'], unique=True)
        batch_op.create_index(batch_op.f('ix_registro_num_repo'), ['num_repo'], unique=True)

    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=True),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('password', sa.String(), nullable=False),
    sa.Column('created_on', sa.DateTime(), nullable=True),
    sa.Column('is_admin', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_created_on'), ['created_on'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_created_on'))

    op.drop_table('users')
    with op.batch_alter_table('registro', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_registro_num_repo'))
        batch_op.drop_index(batch_op.f('ix_registro_num_quality'))
        batch_op.drop_index(batch_op.f('ix_registro_num_bugs'))
        batch_op.drop_index(batch_op.f('ix_registro_num_app'))
        batch_op.drop_index(batch_op.f('ix_registro_num_analisis'))

    op.drop_table('registro')
    op.drop_table('proveedor')
    with op.batch_alter_table('metricas', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_metricas_vulnerabilities'))
        batch_op.drop_index(batch_op.f('ix_metricas_sqale_rating'))
        batch_op.drop_index(batch_op.f('ix_metricas_sqale_index'))
        batch_op.drop_index(batch_op.f('ix_metricas_sqale_debt_ratio'))
        batch_op.drop_index(batch_op.f('ix_metricas_security_rating'))
        batch_op.drop_index(batch_op.f('ix_metricas_reliability_rating'))
        batch_op.drop_index(batch_op.f('ix_metricas_ncloc'))
        batch_op.drop_index(batch_op.f('ix_metricas_duplicated_line_density'))
        batch_op.drop_index(batch_op.f('ix_metricas_coverage'))
        batch_op.drop_index(batch_op.f('ix_metricas_complexity'))
        batch_op.drop_index(batch_op.f('ix_metricas_code_smells'))
        batch_op.drop_index(batch_op.f('ix_metricas_bugs'))

    op.drop_table('metricas')
    with op.batch_alter_table('historico', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_historico_vulnerabilities'))
        batch_op.drop_index(batch_op.f('ix_historico_sqale_rating'))
        batch_op.drop_index(batch_op.f('ix_historico_sqale_index'))
        batch_op.drop_index(batch_op.f('ix_historico_sqale_debt_ratio'))
        batch_op.drop_index(batch_op.f('ix_historico_security_rating'))
        batch_op.drop_index(batch_op.f('ix_historico_reliability_rating'))
        batch_op.drop_index(batch_op.f('ix_historico_ncloc'))
        batch_op.drop_index(batch_op.f('ix_historico_duplicated_line_density'))
        batch_op.drop_index(batch_op.f('ix_historico_coverage'))
        batch_op.drop_index(batch_op.f('ix_historico_complexity'))
        batch_op.drop_index(batch_op.f('ix_historico_code_smells'))
        batch_op.drop_index(batch_op.f('ix_historico_bugs'))

    op.drop_table('historico')
    with op.batch_alter_table('daily', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_daily_repo'))

    op.drop_table('daily')
    # ### end Alembic commands ###
