"""Increase project field size to 128 characters

Revision ID: 9848edb1a6dd
Revises: 49ebb3edbbe1
Create Date: 2025-12-16 17:35:48.245285

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9848edb1a6dd'
down_revision = '49ebb3edbbe1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('stats', schema=None) as batch_op:
        batch_op.drop_index('ix_stats_repos')

    op.drop_table('stats')
    with op.batch_alter_table('daily', schema=None) as batch_op:
        batch_op.drop_index('ix_daily_repo')
        batch_op.create_index(batch_op.f('ix_daily_repo'), ['repo'], unique=False)
        batch_op.create_index('idx_daily_aplicacion_date', ['aplicacion', 'created_on'], unique=False)
        batch_op.create_index(batch_op.f('ix_daily_aplicacion'), ['aplicacion'], unique=False)

    with op.batch_alter_table('historico', schema=None) as batch_op:
        batch_op.alter_column('project',
               existing_type=sa.VARCHAR(length=64),
               type_=sa.String(length=128),
               existing_nullable=True)

    with op.batch_alter_table('metricas', schema=None) as batch_op:
        batch_op.alter_column('project',
               existing_type=sa.VARCHAR(length=64),
               type_=sa.String(length=128),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('metricas', schema=None) as batch_op:
        batch_op.alter_column('project',
               existing_type=sa.String(length=128),
               type_=sa.VARCHAR(length=64),
               existing_nullable=True)

    with op.batch_alter_table('historico', schema=None) as batch_op:
        batch_op.alter_column('project',
               existing_type=sa.String(length=128),
               type_=sa.VARCHAR(length=64),
               existing_nullable=True)

    with op.batch_alter_table('daily', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_daily_aplicacion'))
        batch_op.drop_index('idx_daily_aplicacion_date')
        batch_op.drop_index(batch_op.f('ix_daily_repo'))
        batch_op.create_index('ix_daily_repo', ['repo'], unique=False)

    op.create_table('stats',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('aplicacion', sa.VARCHAR(length=64), nullable=False),
    sa.Column('repos', sa.INTEGER(), nullable=False),
    sa.Column('reliability_label', sa.TEXT(), nullable=True),
    sa.Column('reliability_rating', sa.INTEGER(), nullable=False),
    sa.Column('sqale_label', sa.TEXT(), nullable=True),
    sa.Column('sqale_rating', sa.INTEGER(), nullable=False),
    sa.Column('security_label', sa.TEXT(), nullable=True),
    sa.Column('security_rating', sa.INTEGER(), nullable=False),
    sa.Column('alert_status_label', sa.TEXT(), nullable=True),
    sa.Column('alert_status_ok', sa.INTEGER(), nullable=False),
    sa.Column('dloc_label', sa.TEXT(), nullable=True),
    sa.Column('dloc_rating', sa.INTEGER(), nullable=False),
    sa.Column('coverage_label', sa.TEXT(), nullable=True),
    sa.Column('coverage_rating', sa.INTEGER(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('aplicacion')
    )
    with op.batch_alter_table('stats', schema=None) as batch_op:
        batch_op.create_index('ix_stats_repos', ['repos'], unique=False)

    # ### end Alembic commands ###
