"""Remove unique constraints from registro fields

Revision ID: a1b2c3d4e5f6
Revises: 9848edb1a6dd
Create Date: 2025-12-18 10:52:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a1b2c3d4e5f6'
down_revision = '9848edb1a6dd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('registro', schema=None) as batch_op:
        # Drop unique constraints from proceso
        batch_op.drop_constraint('registro_proceso_key', type_='unique')

        # Drop unique constraints from numeric fields
        batch_op.drop_constraint('registro_num_app_key', type_='unique')
        batch_op.drop_constraint('registro_num_repo_key', type_='unique')
        batch_op.drop_constraint('registro_num_bugs_key', type_='unique')
        batch_op.drop_constraint('registro_num_quality_key', type_='unique')
        batch_op.drop_constraint('registro_num_analisis_key', type_='unique')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('registro', schema=None) as batch_op:
        # Restore unique constraints
        batch_op.create_unique_constraint('registro_num_analisis_key', ['num_analisis'])
        batch_op.create_unique_constraint('registro_num_quality_key', ['num_quality'])
        batch_op.create_unique_constraint('registro_num_bugs_key', ['num_bugs'])
        batch_op.create_unique_constraint('registro_num_repo_key', ['num_repo'])
        batch_op.create_unique_constraint('registro_num_app_key', ['num_app'])
        batch_op.create_unique_constraint('registro_proceso_key', ['proceso'])
    # ### end Alembic commands ###
